version: '3.8'

services:
  # searchindex:
  #   image: opensearchproject/opensearch
  #   volumes:
  #       - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
  #       - "searchindexdata:/usr/share/opensearch/data"
  #       # - "./certs:/usr/share/opensearch/config/certificates:ro"
  #   ports:
  #     - 9200:9200
  #     # - 9600:9600 # required for Performance Analyzer
  #   environment:
  #     - discovery.type=single-node
  #   # healthcheck:
  #   #   test: [ "CMD", "curl",  "--fail" , "http://searchindex:9200/_cluster/health?wait_for_status=yellow", "||", "exit", "1" ]
  #   #   interval: 5s
  #   #   timeout: 60s
  # searchdashboard:
  #   image: opensearchproject/opensearch-dashboards
  #   ports:
  #     - 5601:5601
  #   volumes:
  #     # - "./certs:/usr/share/opensearch-dashboards/config/certificates:ro"
  #     - "./opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
  apiserver: 
    build:
      context: apiserver
    ports: 
      - 8000:8000
    volumes:
      - ./apiserver:/app
    # depends_on:
    #   searchindex:
    #    condition: service_healthy
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090

volumes:
  prometheus:
  # searchindexdata: